"""
content_bank.py
100 narasi Kisah 25 Nabi (4 episode per nabi), ditulis sekali & disimpan lokal —
TIDAK butuh API berbayar untuk generate teks harian.

Target ~70-90 kata per episode (~30 detik voiceover) untuk durasi Reels yang lebih ideal.

Narasi merujuk pada garis besar kisah yang umum dikenal dalam riwayat Islam.
DISARANKAN: baca ulang/review sekali oleh yang paham agama sebelum dipakai
publik, terutama karena ini menyangkut keyakinan agama.

Struktur: NABI_STORIES["Nama Nabi"] = [episode1, episode2, episode3, episode4]
"""

NABI_STORIES = {
    "Adam": [
        "Kisah 25 Nabi dimulai dari Nabi Adam, manusia pertama yang diciptakan Allah dari tanah liat lalu ditiupkan ruh ke dalamnya. Sebagai kemuliaan baginya, Allah mengajarkan Adam nama-nama segala sesuatu, sebuah ilmu yang bahkan tidak diketahui para malaikat sekalipun. Karena itu, Allah memerintahkan seluruh malaikat bersujud hormat kepada Adam sebagai penghormatan. Semua malaikat taat menjalankan perintah tersebut, kecuali Iblis yang menolak dengan sombong karena merasa lebih mulia karena diciptakan dari api. Kisah ini akan berlanjut besok, ikuti terus ya.",
        "Melanjutkan kisah kemarin, Adam kemudian ditempatkan tinggal di surga bersama pasangannya, Hawa, yang diciptakan untuk menemaninya. Keduanya diperbolehkan menikmati segala kenikmatan yang ada di surga dengan bebas, kecuali satu larangan yaitu tidak boleh mendekati dan memakan buah dari satu pohon tertentu. Iblis yang telah diusir dari surga karena kesombongannya bersumpah di hadapan Allah untuk terus menyesatkan keturunan Adam sepanjang zaman. Ia pun mulai membisikkan tipu daya kepada Adam dan Hawa. Bagaimana kelanjutannya, simak besok.",
        "Bujukan halus Iblis akhirnya berhasil membuat Adam dan Hawa lalai dan tergoda mendekati pohon terlarang tersebut, hingga keduanya memakan buahnya. Menyadari kesalahan yang telah diperbuat, Adam dan Hawa segera bersimpuh memohon ampun kepada Allah dengan penuh penyesalan dan kesungguhan hati. Allah Yang Maha Pengampun menerima taubat keduanya, namun sebagai bagian dari takdir dan rencana besar-Nya, mereka tetap diturunkan dari surga ke bumi untuk memulai kehidupan sebagai manusia. Lanjutannya besok, saksikan terus.",
        "Di bumi, Adam dan Hawa memulai kehidupan baru sebagai manusia pertama sekaligus nabi pertama yang bertugas membimbing keturunannya kelak. Mereka mengajarkan cara bercocok tanam, membangun tempat tinggal, beribadah kepada Allah, dan menjalani kehidupan sesuai petunjuk yang telah diberikan. Dari pasangan inilah seluruh umat manusia berasal hingga hari ini. Hikmah besar dari kisah Nabi Adam: sebuah kesalahan bukanlah akhir dari segalanya, selama diiringi taubat yang tulus, pintu ampunan Allah akan selalu terbuka lebar. Besok kita lanjut ke kisah Nabi Idris.",
    ],
    "Idris": [
        "Kisah hari ini tentang Nabi Idris, salah satu keturunan Nabi Adam yang dikenal sebagai manusia paling awal yang dianugerahi ilmu pengetahuan sangat luas oleh Allah. Ia dikenal sangat cerdas, tekun beribadah, dan disebut-sebut sebagai orang pertama yang pandai menulis menggunakan pena serta mempelajari ilmu perbintangan dan hitungan. Kesalehan dan kecerdasannya membuatnya sangat dihormati dan dicintai oleh masyarakat di sekitarnya pada masa itu. Lanjutannya besok.",
        "Nabi Idris dikenal sangat gigih mendakwahkan kaumnya agar kembali menyembah Allah semata dan meninggalkan berbagai kebiasaan buruk yang berkembang pada masanya. Ia mengajarkan pentingnya kejujuran dalam berdagang, keadilan dalam bermasyarakat, serta menjaga kebersihan diri dan lingkungan. Ketekunannya beribadah siang dan malam membuat kedudukannya sangat mulia di sisi Allah, bahkan ia disebut sebagai orang yang jujur dan benar. Bagaimana kisah selanjutnya, ikuti besok.",
        "Salah satu keistimewaan Nabi Idris yang dikenal luas dalam riwayat adalah kedudukannya yang sangat tinggi di sisi Allah, sebagai buah dari kesabaran dan keteguhannya beribadah sepanjang hidupnya. Ia menghadapi berbagai tantangan dari kaumnya yang enggan berubah dari kebiasaan lama mereka, namun tetap istiqamah menyampaikan kebenaran meski hanya sedikit yang mau mengikutinya dengan sungguh-sungguh. Lanjutan besok.",
        "Nabi Idris mengajarkan kepada kita bahwa ilmu pengetahuan dan ibadah harus selalu berjalan beriringan, tidak boleh dipisahkan satu sama lain. Kecerdasan dan keluasan ilmunya digunakan sepenuhnya untuk kebaikan umat, bukan untuk kesombongan atau kepentingan pribadi semata. Hikmahnya: semakin tinggi ilmu yang dimiliki seseorang, semestinya semakin rendah hati pula sikapnya dan semakin dekat ia kepada Allah. Besok kita masuk ke kisah Nabi Nuh yang penuh ujian besar.",
    ],
    "Nuh": [
        "Nabi Nuh diutus Allah kepada kaumnya yang telah jauh tersesat, meninggalkan penyembahan kepada Allah dan beralih menyembah berhala-berhala buatan tangan mereka sendiri. Selama ratusan tahun lamanya, Nabi Nuh menyeru kaumnya siang dan malam, secara terang-terangan maupun sembunyi-sembunyi, agar kembali menyembah Allah semata. Namun kesabarannya yang luar biasa hanya dibalas dengan ejekan, hinaan, bahkan ancaman dari kaumnya sendiri. Kisah ini berlanjut besok.",
        "Karena penolakan kaumnya yang terus-menerus dan tak kunjung berubah, Allah memerintahkan Nabi Nuh untuk membangun sebuah kapal yang sangat besar, padahal lokasinya jauh dari lautan. Perintah ini membuatnya semakin diejek dan dianggap gila oleh masyarakat sekitar. Meski demikian, Nabi Nuh tetap taat menjalankan perintah tersebut dengan sabar sambil terus melanjutkan dakwahnya kepada kaumnya. Ada apa di balik perintah pembangunan kapal ini? Simak besok.",
        "Ketika kapal akhirnya selesai dibangun, datanglah banjir besar yang menenggelamkan seluruh kaum yang durhaka dan enggan beriman. Nabi Nuh beserta para pengikutnya yang beriman, serta sepasang dari setiap jenis makhluk hidup, selamat berlindung di dalam kapal tersebut atas izin Allah. Bahkan salah satu putra Nabi Nuh sendiri menolak untuk ikut naik ke kapal dan akhirnya tenggelam karena keingkarannya. Lanjutannya besok.",
        "Setelah air bah surut, kapal Nabi Nuh mendarat di sebuah daratan, dan kehidupan pun dimulai kembali dari mereka yang selamat. Kisah panjang perjuangan Nabi Nuh ini mengajarkan bahwa kesabaran dalam berdakwah harus selalu disertai keyakinan penuh akan pertolongan Allah, walaupun hasilnya terlihat sangat lambat datangnya, bahkan memakan waktu ratusan tahun sekalipun. Besok kita lanjut ke kisah Nabi Hud.",
    ],
    "Hud": [
        "Nabi Hud diutus kepada kaum 'Ad, sebuah kaum yang dikenal memiliki fisik yang sangat kuat dan mahir membangun bangunan-bangunan tinggi nan megah di antara bukit-bukit. Namun kekuatan dan kemegahan yang mereka miliki justru membuat mereka menjadi sombong dan berpaling menyembah berhala selain Allah. Nabi Hud dengan lembut mengingatkan kaumnya agar bersyukur atas nikmat yang telah diberikan, bukan malah berbangga diri secara berlebihan. Lanjutannya besok.",
        "Kaum 'Ad menolak seruan Nabi Hud dengan penuh kesombongan, bahkan menantangnya untuk segera mendatangkan azab jika benar ia adalah utusan Allah seperti yang diklaimnya. Nabi Hud tetap bersabar mengingatkan mereka bahwa sehebat apapun kekuatan fisik dan bangunan yang mereka miliki, semua itu tidak akan pernah mampu melawan kehendak dan kekuasaan Allah. Bagaimana akhir dari kesombongan mereka? Simak besok.",
        "Karena terus-menerus mengingkari peringatan yang telah disampaikan, Allah akhirnya mengirimkan angin kencang yang menghancurkan kaum 'Ad selama beberapa hari berturut-turut tanpa henti. Angin dahsyat tersebut memusnahkan seluruh kaum yang dahulu begitu bangga dengan kekuatan fisik dan bangunan megah mereka. Nabi Hud beserta para pengikutnya yang beriman diselamatkan Allah dari azab yang mengerikan tersebut. Lanjutannya besok.",
        "Kisah Nabi Hud mengajarkan kepada kita bahwa kekuatan fisik dan kemegahan duniawi, sebesar apapun itu, tidak akan pernah ada artinya di hadapan kehendak Allah jika digunakan untuk kesombongan semata. Hikmah pentingnya adalah untuk selalu rendah hati dan senantiasa bersyukur atas segala nikmat yang telah diberikan kepada kita. Besok kita lanjut ke kisah Nabi Saleh.",
    ],
    "Saleh": [
        "Nabi Saleh diutus kepada kaum Tsamud yang tinggal di daerah pegunungan dan sangat terampil memahat rumah-rumah megah dari batu-batu besar. Sayangnya, mereka juga tersesat menyembah berhala selain Allah. Nabi Saleh mengajak kaumnya untuk kembali menyembah Allah semata, namun kaumnya justru meminta bukti berupa sebuah mukjizat nyata sebagai syarat agar mereka mau beriman kepadanya. Lanjutannya besok.",
        "Sebagai mukjizat yang nyata, Allah mengeluarkan seekor unta betina dari celah bebatuan sebagai tanda kebenaran kenabian Saleh, dengan syarat kaum Tsamud tidak boleh menyakiti maupun mengganggu unta tersebut sedikit pun. Sebagian kaum akhirnya beriman menyaksikan mukjizat ini, namun sebagian besar lainnya tetap ingkar dan diam-diam merencanakan untuk membunuh unta tersebut. Apa yang terjadi selanjutnya? Simak besok.",
        "Kaum Tsamud yang durhaka akhirnya benar-benar membunuh unta tersebut, melanggar perjanjian yang telah mereka sepakati sebelumnya. Nabi Saleh pun memperingatkan bahwa azab Allah akan datang menimpa mereka dalam waktu tiga hari saja. Benar saja, tepat pada waktunya, suara gemuruh yang sangat dahsyat menghancurkan seluruh kaum yang ingkar tersebut, sementara Nabi Saleh dan para pengikutnya yang beriman selamat. Lanjutannya besok.",
        "Kisah Nabi Saleh mengingatkan kita untuk senantiasa menepati janji dan tidak merusak amanah yang telah dipercayakan kepada kita, sekecil apapun amanah itu terlihat di mata manusia. Pelanggaran terhadap perjanjian dengan Allah selalu akan membawa konsekuensi yang nyata cepat atau lambat. Besok kita masuk ke kisah Nabi Ibrahim, yang dikenal sebagai bapak para nabi.",
    ],
    "Ibrahim": [
        "Nabi Ibrahim tumbuh besar di tengah lingkungan masyarakat yang menyembah berhala, bahkan ayahnya sendiri berprofesi sebagai pembuat dan penjual patung-patung berhala. Sejak usia muda, Ibrahim telah mempertanyakan logika menyembah benda mati buatan tangan manusia sendiri, dan ia terus mencari kebenaran tentang siapa sesungguhnya Tuhan yang patut disembah oleh seluruh alam semesta ini. Lanjutannya besok.",
        "Untuk membuktikan kesalahan besar dalam penyembahan berhala kepada kaumnya, Nabi Ibrahim menghancurkan seluruh berhala tersebut kecuali satu yang paling besar ukurannya. Ketika ditanya oleh kaumnya siapa pelakunya, ia menjawab dengan bijak agar kaumnya sendiri menyadari betapa tidak berdayanya berhala-berhala yang selama ini mereka sembah dan agungkan. Kemarahan kaumnya pun memuncak mendengar jawaban tersebut. Bagaimana kelanjutannya, simak besok.",
        "Karena tindakan beraninya tersebut, Nabi Ibrahim dijatuhi hukuman dibakar hidup-hidup di hadapan orang banyak atas perintah Raja Namrud yang zalim. Namun atas izin dan kekuasaan Allah, api yang berkobar besar tersebut seketika berubah menjadi dingin dan sama sekali tidak melukainya. Kejadian luar biasa ini menjadi salah satu mukjizat terbesar yang menunjukkan pertolongan Allah bagi hamba yang teguh dalam kebenaran. Lanjutannya besok.",
        "Nabi Ibrahim kemudian dikenal luas sepanjang sejarah sebagai bapak para nabi, karena garis keturunannya melahirkan banyak nabi-nabi besar setelahnya, termasuk Nabi Ismail dan Nabi Ishaq. Hikmah besar dari kisah panjangnya ini adalah bahwa keteguhan seseorang dalam mempertahankan kebenaran akan selalu mendapatkan pertolongan Allah, betapapun besar dan beratnya tantangan yang harus dihadapi. Besok kita lanjut ke kisah Nabi Luth.",
    ],
    "Luth": [
        "Nabi Luth diutus kepada penduduk kaum Sodom, sebuah kaum yang dikenal melakukan perbuatan keji yang belum pernah dilakukan oleh umat manusia mana pun sebelumnya. Nabi Luth, yang juga merupakan keponakan dari Nabi Ibrahim, dengan penuh kesabaran mengajak kaumnya untuk meninggalkan perbuatan tersebut dan kembali ke jalan yang benar. Namun ajakan tulusnya itu hanya dibalas dengan ejekan dan penolakan keras. Lanjutannya besok.",
        "Kaum Nabi Luth semakin durhaka dari hari ke hari, bahkan secara terang-terangan mengancam akan mengusirnya beserta seluruh pengikutnya dari kota apabila ia terus-menerus mengingatkan mereka akan perbuatan keji tersebut. Nabi Luth tetap teguh menyampaikan kebenaran, meski hatinya sangat sedih karena tidak banyak yang mau menerima ajakannya, bahkan dari kalangan keluarganya sendiri. Bagaimana kelanjutan kisah ini, simak besok.",
        "Allah akhirnya mengutus para malaikat dalam wujud tamu manusia untuk memperingatkan Nabi Luth agar segera membawa keluarganya yang beriman pergi meninggalkan kota tersebut sebelum azab besar diturunkan. Istrinya yang tidak beriman dan diam-diam bersekongkol dengan kaum yang durhaka dilarang untuk ikut serta dalam kepergian tersebut. Lanjutannya besok.",
        "Setelah Nabi Luth dan seluruh keluarganya yang beriman berhasil pergi meninggalkan kota, seluruh negeri kaum Sodom dihancurkan total sebagai azab yang setimpal atas perbuatan keji yang mereka lakukan selama ini. Kisah ini mengajarkan bahwa kedekatan hubungan keluarga sekalipun tidak akan pernah menjamin keselamatan seseorang tanpa disertai keimanan pribadi yang kuat kepada Allah. Besok kita lanjut ke kisah Nabi Ismail.",
    ],
    "Ismail": [
        "Nabi Ismail adalah putra Nabi Ibrahim dari istrinya, Siti Hajar. Sejak masih bayi, Ismail dan ibunya ditempatkan tinggal di sebuah lembah yang sangat tandus dan gersang, yang kini dikenal sebagai kota Mekah, sesuai perintah Allah kepada Nabi Ibrahim. Ketika persediaan air habis, Siti Hajar berlari-lari kecil mencari air antara bukit Shafa dan Marwah, hingga akhirnya muncullah sumber mata air Zamzam yang tidak pernah kering hingga sekarang. Lanjutannya besok.",
        "Ismail tumbuh menjadi seorang anak yang sangat saleh dan taat kepada kedua orang tuanya. Ketika beranjak remaja, Nabi Ibrahim menerima perintah melalui mimpi untuk menyembelih putra tercintanya sendiri sebagai bentuk ujian ketaatan yang sangat berat. Dengan penuh kesabaran dan keikhlasan luar biasa, Ismail justru mendukung penuh ayahnya untuk melaksanakan perintah tersebut demi ketaatan kepada Allah semata. Bagaimana kelanjutannya, simak besok.",
        "Tepat pada saat penyembelihan hendak dilaksanakan, Allah menggantikan posisi Ismail dengan seekor domba sebagai bentuk kasih sayang-Nya atas ketaatan luar biasa yang ditunjukkan oleh ayah dan anak ini. Peristiwa penuh hikmah inilah yang kemudian menjadi asal-usul dari ibadah kurban yang dilaksanakan oleh umat Islam hingga hari ini setiap perayaan Idul Adha. Lanjutannya besok.",
        "Nabi Ismail bersama sang ayah, Nabi Ibrahim, kemudian bahu-membahu membangun Ka'bah di kota Mekah sebagai rumah ibadah pertama bagi seluruh umat manusia untuk menyembah Allah. Hikmah besar dari kisah ini adalah bahwa ketaatan penuh kepada Allah, meskipun terasa sangat berat pada awalnya, pada akhirnya akan selalu membawa kebaikan yang tidak pernah terduga sebelumnya. Besok kita lanjut ke kisah Nabi Ishaq.",
    ],
    "Ishaq": [
        "Nabi Ishaq adalah putra Nabi Ibrahim dari istrinya yang lain, Sarah, yang terlahir di usia yang sudah sangat lanjut sebagai sebuah kabar gembira yang disampaikan langsung oleh para malaikat. Kelahirannya menjadi bukti nyata akan kekuasaan Allah yang tidak pernah terbatas oleh logika dan kebiasaan umum manusia. Ishaq tumbuh menjadi pribadi yang sangat saleh, mengikuti jejak langkah ayahnya dengan penuh ketaatan. Lanjutannya besok.",
        "Nabi Ishaq melanjutkan estafet dakwah ayahnya untuk menyerukan tauhid kepada kaumnya di wilayah yang kini dikenal sebagai daerah Palestina. Ia dikenal sangat bijaksana dalam menyelesaikan berbagai persoalan yang dihadapi kaumnya, serta senantiasa menjaga hubungan yang harmonis dengan para tetangga di sekitar tempat tinggalnya, meski hidup di tengah masyarakat yang beragam keyakinan. Bagaimana kelanjutan kisahnya, simak besok.",
        "Dari garis keturunan Nabi Ishaq inilah kelak lahir banyak sekali nabi-nabi besar lainnya, termasuk di antaranya Nabi Yaqub beserta seluruh keturunannya yang mulia. Ia senantiasa mengajarkan pentingnya menjaga hubungan baik antar keluarga besar serta konsistensi dalam menyembah Allah semata, di tengah pergaulan masyarakat yang sangat beragam pada masa itu. Lanjutannya besok.",
        "Kisah Nabi Ishaq mengajarkan kepada kita bahwa keberkahan sebuah keluarga sesungguhnya terletak pada konsistensi menjaga keimanan yang diwariskan dari satu generasi ke generasi berikutnya secara berkelanjutan. Hikmahnya, warisan terbaik yang dapat diberikan orang tua kepada anak-anaknya bukanlah semata harta benda, melainkan pondasi keimanan yang kokoh dan kuat. Besok kita lanjut ke kisah Nabi Yaqub.",
    ],
    "Yaqub": [
        "Nabi Yaqub adalah putra Nabi Ishaq yang dikaruniai dua belas orang putra, salah satu di antaranya adalah Yusuf yang sangat ia sayangi karena kesalehan serta akhlaknya yang begitu mulia sejak kecil. Kecintaan yang berlebih ini kemudian menimbulkan rasa cemburu yang mendalam dari saudara-saudara Yusuf yang lainnya. Nabi Yaqub sendiri dikenal luas sebagai sosok ayah yang penuh kesabaran dan kebijaksanaan dalam mendidik anak-anaknya. Lanjutannya besok.",
        "Kecemburuan yang dipendam oleh saudara-saudara Yusuf akhirnya memuncak hingga mereka merencanakan sesuatu yang mencelakainya. Setelah kehilangan Yusuf, Nabi Yaqub mengalami kesedihan yang sangat mendalam selama bertahun-tahun lamanya, hingga diriwayatkan matanya memutih karena terlalu banyak menangis. Meski demikian, ia tidak pernah sekalipun berputus asa dan terus memanjatkan doa kepada Allah tanpa henti. Bagaimana kelanjutannya, simak besok.",
        "Bertahun-tahun kemudian, setelah penantian yang begitu panjang, Nabi Yaqub akhirnya dipertemukan kembali dengan Yusuf yang ternyata telah menjadi seorang pejabat besar dan berpengaruh di Mesir. Pertemuan tersebut berlangsung dengan sangat mengharukan setelah bertahun-tahun keduanya berpisah dalam kesedihan. Kesabaran panjang Nabi Yaqub akhirnya membuahkan kebahagiaan yang luar biasa besar. Lanjutannya besok.",
        "Kisah Nabi Yaqub mengajarkan kepada kita bahwa kesabaran dalam menghadapi ujian yang begitu berat, sekalipun terasa sangat lama waktunya, pada akhirnya akan selalu berbuah hasil yang manis apabila disertai dengan doa dan keyakinan penuh kepada Allah tanpa pernah putus asa. Besok kita lanjut ke kisah lengkap Nabi Yusuf yang penuh liku kehidupan.",
    ],
    "Yusuf": [
        "Nabi Yusuf sejak kecil dikenal memiliki paras yang sangat rupawan dan pernah bermimpi melihat sebelas bintang, matahari, dan bulan bersujud kepadanya. Karena diliputi rasa cemburu yang mendalam, saudara-saudaranya membuang Yusuf ke dalam sebuah sumur tua ketika mereka sedang bepergian bersama, lalu berbohong kepada sang ayah bahwa Yusuf telah dimakan oleh serigala liar. Lanjutannya besok.",
        "Yusuf kemudian ditemukan oleh sebuah kafilah dagang yang lewat, dan akhirnya dijual sebagai seorang budak kepada seorang pejabat istana di Mesir. Di sanalah ia tumbuh menjadi seorang pemuda yang sangat tampan dan berakhlak mulia, namun harus menghadapi godaan besar dari istri pejabat tersebut, hingga akhirnya ia difitnah dan dijebloskan ke dalam penjara meskipun sesungguhnya ia sama sekali tidak bersalah. Bagaimana kelanjutannya, simak besok.",
        "Selama berada di dalam penjara, Nabi Yusuf dikenal sangat pandai dalam menafsirkan mimpi orang lain. Kemampuan istimewa inilah yang akhirnya membawanya keluar dari penjara, setelah berhasil menafsirkan mimpi Raja Mesir tentang tujuh tahun masa subur dan tujuh tahun masa paceklik yang akan datang, hingga ia pun diangkat menjadi pejabat tinggi yang mengatur seluruh persediaan pangan negeri tersebut. Lanjutannya besok.",
        "Ketika masa paceklik benar-benar melanda, saudara-saudara Yusuf yang dahulu pernah mencelakainya datang jauh-jauh ke Mesir untuk mencari bantuan pangan, tanpa mengenali sama sekali bahwa pejabat yang mereka temui adalah Yusuf sendiri. Dengan lapang dada dan penuh kebesaran hati, Yusuf memaafkan seluruh kesalahan mereka dan mempertemukan kembali seluruh keluarganya, termasuk ayahnya, Nabi Yaqub. Hikmahnya: memaafkan adalah sebuah kekuatan besar, bukan kelemahan. Besok kita lanjut ke kisah Nabi Ayyub.",
    ],
    "Ayyub": [
        "Nabi Ayyub dikenal luas sebagai seorang hamba Allah yang sangat kaya raya, namun tetap rendah hati dan sangat dermawan kepada sesama. Sebagai bagian dari ujian keimanan yang berat, Allah menguji Nabi Ayyub dengan menghilangkan seluruh harta kekayaannya, seluruh anak-anaknya, serta kesehatan tubuhnya secara bertahap satu demi satu. Meski demikian, ia tetap bersabar dengan penuh ketabahan dan tidak pernah sekalipun berhenti bersyukur kepada Allah. Lanjutannya besok.",
        "Ujian penyakit berat yang diderita Nabi Ayyub berlangsung selama bertahun-tahun lamanya, hingga banyak orang di sekitarnya yang mulai menjauhinya karena kondisi tersebut. Namun sang istri tetap setia menemani dan merawatnya dengan penuh kasih sayang sepanjang waktu, meskipun hidup dalam kesulitan dan keterbatasan yang sangat besar. Nabi Ayyub tetap tidak pernah sekalipun mengeluh kepada Allah atas semua ujian yang menimpanya. Bagaimana kelanjutannya, simak besok.",
        "Setelah bertahun-tahun bersabar tanpa henti, Nabi Ayyub akhirnya memanjatkan doa memohon kesembuhan dengan penuh kerendahan hati kepada Allah. Doa tersebut dikabulkan dengan dimunculkannya sebuah mata air segar untuk mandi dan minum, yang seketika menyembuhkan seluruh penyakit yang dideritanya selama ini. Bahkan seluruh harta kekayaannya pun dikembalikan oleh Allah, bahkan dilipatgandakan jumlahnya. Lanjutannya besok.",
        "Kisah Nabi Ayyub menjadi sebuah teladan besar tentang kesabaran dalam menghadapi ujian hidup seberat apapun tanpa pernah berputus asa dari rahmat dan kasih sayang Allah. Hikmahnya, di balik setiap kesulitan besar yang dihadapi dengan penuh kesabaran, pasti ada jalan keluar terbaik yang telah Allah siapkan pada waktunya. Besok kita lanjut ke kisah Nabi Syu'aib.",
    ],
    "Syu'aib": [
        "Nabi Syu'aib diutus kepada penduduk negeri Madyan yang dikenal sangat curang dalam praktik berdagang mereka sehari-hari, sering kali mengurangi takaran timbangan demi keuntungan pribadi semata tanpa memikirkan kerugian orang lain. Nabi Syu'aib dengan penuh kesabaran mengajak kaumnya untuk senantiasa berlaku jujur dalam berniaga dan tidak merugikan sesama manusia dalam bentuk apapun. Lanjutannya besok.",
        "Kaum Madyan menolak keras seruan Nabi Syu'aib dan bahkan menganggap ajaran yang disampaikannya sebagai ancaman besar terhadap kebiasaan berdagang mereka yang telah dilakukan secara turun-temurun sejak lama. Mereka bahkan mengancam akan mengusirnya dari negeri tersebut. Nabi Syu'aib tetap bersabar mengingatkan bahwa kecurangan hanya akan membawa kehancuran, bukan keberkahan yang sesungguhnya diharapkan. Bagaimana kelanjutannya, simak besok.",
        "Karena terus-menerus menolak dan mengingkari peringatan yang telah disampaikan berulang kali, kaum Madyan akhirnya ditimpa azab berupa suara yang sangat keras menggelegar yang membinasakan mereka semua secara serentak. Nabi Syu'aib beserta para pengikutnya yang beriman diselamatkan sepenuhnya oleh Allah dari azab mengerikan tersebut. Lanjutannya besok.",
        "Kisah Nabi Syu'aib mengajarkan kepada kita betapa pentingnya kejujuran dalam berbisnis dan bermuamalah dengan sesama manusia dalam kehidupan sehari-hari. Hikmahnya, keberkahan rezeki yang sesungguhnya datang dari cara yang jujur dan halal, bukan dari kecurangan sekalipun terlihat menguntungkan secara sesaat di mata manusia. Besok kita lanjut ke kisah Nabi Musa, salah satu kisah paling panjang dalam Al-Qur'an.",
    ],
    "Musa": [
        "Nabi Musa lahir pada masa kekuasaan Firaun yang sangat zalim, yang memerintahkan pembunuhan terhadap setiap bayi laki-laki dari kalangan Bani Israil karena takut akan sebuah ramalan bahwa kelak salah satu dari mereka akan menggulingkan kekuasaannya. Untuk menyelamatkan sang bayi, ibu Musa menghanyutkannya di Sungai Nil di dalam sebuah peti kayu, hingga akhirnya ditemukan dan justru dipelihara oleh istri Firaun sendiri tanpa mengetahui asal-usulnya. Lanjutannya besok.",
        "Musa tumbuh dewasa di dalam lingkungan istana Firaun, namun setelah terjadi sebuah insiden yang tidak disengaja, ia terpaksa melarikan diri jauh ke negeri Madyan untuk menghindari hukuman. Di sanalah Allah untuk pertama kalinya memberinya wahyu kenabian di lembah suci bernama Thuwa, memerintahkannya untuk kembali ke Mesir guna menyeru Firaun agar mau beriman kepada Allah Yang Maha Esa. Bagaimana kelanjutannya, simak besok.",
        "Musa kembali ke Mesir bersama saudaranya, Nabi Harun, untuk menghadapi Firaun yang dengan sombong mengaku dirinya sebagai tuhan yang harus disembah. Dengan mukjizat besar berupa tongkat yang berubah menjadi seekor ular nyata dan tangan yang mengeluarkan cahaya terang, Musa menunjukkan kebenaran risalah kenabiannya. Namun Firaun tetap bersikeras sombong dan menolak untuk beriman kepada Allah. Lanjutannya besok.",
        "Puncak dari kisah panjang ini terjadi ketika Nabi Musa membawa seluruh Bani Israil keluar meninggalkan Mesir, dan Allah membelah Laut Merah menjadi dua bagian untuk menyelamatkan mereka dari kejaran pasukan Firaun yang mengejar dari belakang. Firaun beserta seluruh pasukannya akhirnya tenggelam di dalam laut tersebut saat berusaha mengejar. Hikmahnya, kesombongan terhadap kekuasaan Allah pada akhirnya akan selalu runtuh, sebesar apapun kekuatan yang dimiliki seseorang. Besok kita lanjut ke kisah Nabi Harun.",
    ],
    "Harun": [
        "Nabi Harun adalah saudara kandung Nabi Musa yang diutus untuk mendampinginya karena kefasihan lidahnya dalam berbicara, membantu menyampaikan risalah kenabian kepada Firaun serta seluruh Bani Israil pada masa itu. Keduanya bekerja sama dengan sangat erat dalam menjalankan tugas dakwah yang penuh dengan tantangan besar tersebut. Lanjutannya besok.",
        "Ketika Nabi Musa pergi menuju Gunung Sinai untuk menerima wahyu langsung dari Allah, Nabi Harun diberi tanggung jawab untuk memimpin seluruh Bani Israil selama kepergian saudaranya tersebut. Namun sepeninggal Musa, sebagian dari Bani Israil justru tergoda untuk membuat dan menyembah sebuah patung anak sapi dari emas, sesuatu yang sangat ditentang keras oleh Nabi Harun meskipun ia tidak sepenuhnya mampu mencegahnya. Bagaimana kelanjutannya, simak besok.",
        "Sekembalinya Nabi Musa dan mendapati kaumnya telah menyembah patung anak sapi tersebut, ia sangat marah kepada saudaranya. Namun Nabi Harun menjelaskan dengan tenang bahwa ia sesungguhnya telah berusaha keras mencegah dan mengingatkan kaumnya, namun mereka tidak mengindahkannya karena khawatir akan terjadi perpecahan besar di antara mereka jika dipaksakan. Lanjutannya besok.",
        "Kisah Nabi Harun mengajarkan kepada kita betapa pentingnya kerja sama yang erat dan saling mendukung dalam kebaikan, sebagaimana yang telah dicontohkan melalui hubungan yang begitu kuat antara dirinya dengan Nabi Musa. Hikmahnya, mencegah terjadinya kemungkaran adalah sebuah kewajiban bagi setiap orang, walaupun hasil akhirnya terkadang tidak selalu sesuai dengan yang diharapkan. Besok kita lanjut ke kisah Nabi Zulkifli.",
    ],
    "Zulkifli": [
        "Nabi Zulkifli dikenal sebagai sosok yang sangat sabar dan teguh dalam menjalankan setiap amanah yang dipercayakan kepadanya. Ia pernah berjanji dengan sungguh-sungguh untuk selalu berpuasa di siang hari, mendirikan salat di malam hari, dan tidak pernah sekalipun marah kepada siapapun, sebuah komitmen besar yang ia jaga dengan sangat konsisten sepanjang hidupnya tanpa pernah mengingkarinya. Lanjutannya besok.",
        "Konsistensi luar biasa yang ditunjukkan Nabi Zulkifli dalam menjaga janjinya kepada Allah membuatnya dikenal luas sebagai teladan kesabaran di kalangan kaumnya pada masa itu. Ia juga dikenal sangat adil dalam memimpin serta menyelesaikan berbagai perselisihan yang terjadi di antara umatnya dengan penuh kebijaksanaan. Bagaimana kelanjutannya, simak besok.",
        "Berbagai riwayat menyebutkan bahwa Nabi Zulkifli tetap istiqamah menjaga ibadahnya meskipun menghadapi berbagai macam godaan dan gangguan yang sengaja dilakukan untuk membuatnya marah atau melalaikan janji besar yang telah ia ucapkan. Ketegaran hati inilah yang membuat namanya diabadikan sebagai salah satu nabi mulia dalam Al-Qur'an hingga saat ini. Lanjutannya besok.",
        "Kisah Nabi Zulkifli mengajarkan kepada kita bahwa menjaga komitmen dan konsistensi dalam beribadah, meskipun terlihat sederhana di mata manusia, sesungguhnya merupakan bentuk kesabaran yang sangat mulia di sisi Allah. Hikmahnya, kesabaran bukan hanya soal menahan musibah besar semata, tetapi juga soal konsisten menjaga janji-janji kecil dalam kehidupan sehari-hari. Besok kita lanjut ke kisah Nabi Daud.",
    ],
    "Daud": [
        "Nabi Daud pada awalnya adalah seorang prajurit muda biasa yang berhasil mengalahkan seorang raksasa bernama Jalut dalam sebuah pertempuran besar, sebuah keberanian luar biasa yang kelak membuatnya diangkat menjadi seorang raja sekaligus nabi bagi Bani Israil. Ia dikenal memiliki suara yang sangat merdu ketika melantunkan pujian dan zikir kepada Allah setiap harinya. Lanjutannya besok.",
        "Sebagai seorang raja, Nabi Daud dikenal sangat adil dalam memutuskan berbagai perkara yang dihadapi oleh rakyatnya sehari-hari. Allah juga menganugerahkannya sebuah mukjizat istimewa berupa kemampuan melunakkan besi hanya dengan kedua tangannya, yang kemudian ia gunakan untuk membuat baju besi sebagai bentuk perlindungan bagi para prajuritnya di medan perang. Bagaimana kelanjutannya, simak besok.",
        "Nabi Daud dikenal sangat rajin beribadah kepada Allah, bahkan disebutkan dalam riwayat memiliki pembagian waktu yang sangat seimbang antara bekerja, beribadah, dan beristirahat setiap harinya. Ia juga rutin menjalankan puasa secara berselang-seling, yaitu sehari berpuasa dan sehari tidak, sebuah kebiasaan ibadah yang sangat dipuji karena keseimbangannya yang luar biasa. Lanjutannya besok.",
        "Kisah Nabi Daud mengajarkan kepada kita betapa pentingnya menjaga keseimbangan hidup antara ibadah, pekerjaan, dan tanggung jawab kepemimpinan yang adil bagi masyarakat luas. Hikmahnya, kekuasaan dan kekuatan besar yang dimiliki seseorang sebaiknya digunakan sepenuhnya untuk menegakkan keadilan, bukan untuk kepentingan dan keuntungan pribadi semata. Besok kita lanjut ke kisah Nabi Sulaiman, putra dari Nabi Daud.",
    ],
    "Sulaiman": [
        "Nabi Sulaiman adalah putra dari Nabi Daud yang dianugerahi sebuah kerajaan yang sangat besar dan luas, bahkan diberikan kemampuan istimewa untuk memahami bahasa hewan serta menguasai angin dan bangsa jin atas izin Allah semata. Meskipun memiliki kekuasaan yang begitu luar biasa besarnya, ia tetap rendah hati dan senantiasa bersyukur kepada Allah atas segala nikmat yang diberikan. Lanjutannya besok.",
        "Suatu ketika, Nabi Sulaiman mendengar kabar tentang Ratu Balqis dari negeri Saba yang menyembah matahari bersama seluruh rakyatnya. Ia pun mengirimkan sepucuk surat berisi ajakan untuk beriman kepada Allah, sebuah langkah dakwah yang sangat bijaksana tanpa disertai paksaan maupun kekerasan sedikit pun kepada mereka. Bagaimana kelanjutannya, simak besok.",
        "Ratu Balqis akhirnya memutuskan untuk berkunjung langsung ke istana megah Nabi Sulaiman, dan setelah menyaksikan sendiri berbagai keajaiban serta kebijaksanaan luar biasa yang dimiliki Sulaiman, ia pun akhirnya menyatakan keimanannya kepada Allah bersama seluruh rakyatnya. Sebuah akhir dari perjalanan dakwah yang penuh kedamaian dan hikmah mendalam. Lanjutannya besok.",
        "Kisah Nabi Sulaiman mengajarkan kepada kita bahwa kekuasaan dan kekayaan besar sekalipun tidak boleh membuat seseorang lupa untuk selalu bersyukur dan tetap rendah hati di hadapan Allah Yang Maha Kuasa. Hikmahnya, dakwah yang dilakukan dengan penuh kebijaksanaan dan hikmah jauh lebih efektif dibandingkan dengan cara paksaan sekalipun. Besok kita lanjut ke kisah Nabi Ilyas.",
    ],
    "Ilyas": [
        "Nabi Ilyas diutus kepada kaum Bani Israil yang pada masa itu telah menyembah sebuah berhala bernama Ba'al, meninggalkan sepenuhnya penyembahan kepada Allah Yang Maha Esa. Dengan penuh keberanian yang luar biasa, Nabi Ilyas mengingatkan kaumnya agar segera kembali kepada ajaran tauhid, meskipun risiko yang harus ia hadapi sangat besar bagi keselamatan dirinya sendiri. Lanjutannya besok.",
        "Kaumnya menolak dengan sangat keras seruan yang disampaikan Nabi Ilyas dan tetap saja mempertahankan kebiasaan menyembah berhala yang telah mereka lakukan sejak lama. Nabi Ilyas terus bersabar berdakwah tanpa henti, meskipun hanya sedikit sekali dari kaumnya yang mau mengikuti kebenaran yang telah ia sampaikan dengan sungguh-sungguh. Bagaimana kelanjutannya, simak besok.",
        "Karena kekerasan hati kaumnya yang tidak kunjung berubah, Allah menimpakan musim kering yang sangat panjang sebagai sebuah teguran bagi mereka semua. Sebagian riwayat menyebutkan hanya ada sedikit sekali pengikut setia yang tetap bertahan bersama Nabi Ilyas dalam mempertahankan ajaran tauhid di tengah tekanan besar dari masyarakat sekitarnya pada masa itu. Lanjutannya besok.",
        "Kisah Nabi Ilyas mengajarkan kepada kita tentang keteguhan dalam mempertahankan akidah yang benar, meskipun berada di lingkungan yang sebagian besar penduduknya telah menyimpang jauh dari ajaran yang benar. Hikmahnya, sebuah kebenaran tidak pernah diukur dari banyaknya jumlah pengikut, melainkan dari keteguhan hati seseorang pada jalan yang diridhai Allah. Besok kita lanjut ke kisah Nabi Ilyasa.",
    ],
    "Ilyasa": [
        "Nabi Ilyasa adalah penerus dari perjuangan dakwah Nabi Ilyas, yang melanjutkan seruan untuk kembali kepada ajaran tauhid di tengah kaum yang masih diliputi kebiasaan lama menyembah berhala. Ia dikenal sangat sabar dan telaten dalam membimbing umatnya secara perlahan agar kembali ke jalan yang benar sesuai petunjuk Allah. Lanjutannya besok.",
        "Nabi Ilyasa dikenal berhasil membimbing sebagian besar kaumnya untuk kembali kepada ajaran tauhid melalui pendekatan yang sangat lembut dan penuh kebijaksanaan, meneruskan estafet perjuangan dakwah yang sebelumnya telah dirintis dengan susah payah oleh Nabi Ilyas. Bagaimana kelanjutannya, simak besok.",
        "Meskipun riwayat detail mengenai kehidupan Nabi Ilyasa tidak sebanyak riwayat nabi-nabi besar lainnya, ia tetap dikenal sebagai sosok yang sangat istiqamah dalam melanjutkan perjuangan dakwah tauhid di tengah-tengah kaumnya, sebuah tugas yang tidaklah mudah namun tetap dijalankannya dengan penuh kesabaran dan ketekunan sepanjang hidupnya. Lanjutannya besok.",
        "Kisah Nabi Ilyasa mengajarkan kepada kita betapa pentingnya melanjutkan estafet kebaikan yang telah dirintis dengan susah payah oleh generasi-generasi sebelumnya. Hikmahnya, sebuah dakwah adalah perjuangan yang harus terus berkelanjutan dan tidak boleh terputus begitu saja, meskipun berganti dari satu generasi ke generasi berikutnya. Besok kita lanjut ke kisah Nabi Yunus.",
    ],
    "Yunus": [
        "Nabi Yunus diutus kepada penduduk kota Ninawa yang menolak dengan sangat keras seruannya untuk beriman kepada Allah Yang Maha Esa. Karena merasa putus asa dengan sikap keras kepala kaumnya, Nabi Yunus memutuskan pergi meninggalkan kotanya tanpa terlebih dahulu meminta izin kepada Allah, sebuah keputusan tergesa-gesa yang kelak sangat ia sesali di kemudian hari. Lanjutannya besok.",
        "Dalam pelariannya tersebut, Nabi Yunus menaiki sebuah kapal yang kemudian diterjang badai laut yang sangat besar dan mengganas. Untuk menyelamatkan seluruh penumpang kapal, mereka melakukan pengundian untuk menentukan siapa yang harus dilempar ke laut, dan undian tersebut jatuh kepada Nabi Yunus. Ia pun akhirnya ditelan oleh seekor ikan besar atas kehendak Allah semata. Bagaimana kelanjutannya, simak besok.",
        "Di dalam perut ikan yang gelap gulita tanpa cahaya sedikit pun, Nabi Yunus menyadari sepenuhnya kesalahan yang telah diperbuatnya dan segera bertaubat dengan sangat sungguh-sungguh, memohon ampun kepada Allah dengan penuh kerendahan hati yang tulus. Allah pun mengabulkan taubatnya dengan menyelamatkannya, mengeluarkannya dari perut ikan tersebut dalam keadaan selamat tanpa kurang suatu apapun. Lanjutannya besok.",
        "Setelah diselamatkan oleh Allah, Nabi Yunus akhirnya kembali kepada kaumnya yang ternyata telah beriman sepenuhnya setelah menyaksikan berbagai tanda kekuasaan Allah yang nyata. Hikmah besar dari kisah ini, sebuah taubat yang tulus, sekalipun dilakukan dalam keadaan yang paling tergelap sekalipun, akan selalu diterima oleh Allah Yang Maha Pengampun. Besok kita lanjut ke kisah Nabi Zakaria.",
    ],
    "Zakaria": [
        "Nabi Zakaria adalah seorang nabi yang telah berusia sangat lanjut namun belum juga dikaruniai seorang keturunan pun bersama istrinya. Ia senantiasa berdoa dengan penuh harap dan kesungguhan kepada Allah agar diberikan seorang anak yang saleh untuk melanjutkan perjuangan dakwahnya kelak, meskipun secara logika manusia biasa usianya sudah sangat tua untuk memiliki keturunan. Lanjutannya besok.",
        "Kesungguhan doa Nabi Zakaria yang tidak pernah putus akhirnya dikabulkan oleh Allah dengan kelahiran seorang putra yang diberi nama Yahya, sebuah kabar gembira yang disampaikan langsung melalui perantara malaikat sebagai tanda kebesaran kekuasaan Allah yang tidak pernah terbatas oleh usia maupun logika manusia biasa. Bagaimana kelanjutannya, simak besok.",
        "Nabi Zakaria mendidik putranya, Yahya, dengan penuh kasih sayang yang mendalam dan senantiasa mengarahkannya untuk menjadi pribadi yang saleh sejak masih kecil. Ia juga dikenal sebagai penjaga dan pengasuh Maryam, yang kelak menjadi ibunda dari Nabi Isa, di Baitul Maqdis pada masa itu. Lanjutannya besok.",
        "Kisah Nabi Zakaria mengajarkan kepada kita bahwa tidak ada satu pun hal yang mustahil bagi Allah, sekalipun secara akal dan logika manusia biasa hal tersebut terlihat sangat tidak mungkin terjadi. Hikmahnya, jangan pernah sekalipun berhenti berdoa dan berharap kepada Allah, betapapun lamanya waktu yang telah dilalui dalam penantian tersebut. Besok kita lanjut ke kisah Nabi Yahya.",
    ],
    "Yahya": [
        "Nabi Yahya adalah putra dari Nabi Zakaria yang sejak masih kecil telah dikaruniai kebijaksanaan yang luar biasa serta kecintaan yang sangat mendalam terhadap ibadah kepada Allah. Ia tumbuh menjadi pribadi yang sangat menjaga dirinya dari perbuatan dosa dan senantiasa bersungguh-sungguh dalam menjalankan setiap perintah Allah sepanjang hidupnya. Lanjutannya besok.",
        "Nabi Yahya dikenal berdakwah dengan sangat tegas mengajak kaumnya untuk segera bertaubat dan meninggalkan seluruh perbuatan maksiat yang mereka lakukan. Ia hidup dengan sangat sederhana dan zuhud, sama sekali tidak tertarik dengan kemewahan dunia, dan fokus sepenuhnya kepada ibadah serta penyampaian kebenaran kepada umatnya. Bagaimana kelanjutannya, simak besok.",
        "Ketegasan luar biasa yang dimiliki Nabi Yahya dalam menyampaikan kebenaran, termasuk keberaniannya menegur penguasa pada masa itu yang melakukan perbuatan melanggar syariat, membuatnya harus menghadapi tantangan yang sangat besar hingga akhir hayatnya, sebagai sebuah bentuk pengorbanan besar dalam menegakkan kebenaran. Lanjutannya besok.",
        "Kisah Nabi Yahya mengajarkan kepada kita tentang keteguhan dalam menyampaikan kebenaran meskipun harus berhadapan dengan risiko yang sangat besar, termasuk dari pihak yang memiliki kekuasaan sekalipun. Hikmahnya, sebuah kebenaran harus tetap disampaikan apapun konsekuensi berat yang harus dihadapi kelak. Besok kita lanjut ke kisah Nabi Isa.",
    ],
    "Isa": [
        "Nabi Isa lahir melalui sebuah mukjizat besar dari Maryam yang sangat saleha, tanpa memiliki seorang ayah sekalipun, sebagai tanda nyata kebesaran kekuasaan Allah yang tidak terbatas. Bahkan sejak masih bayi, Nabi Isa telah mampu berbicara untuk membela kesucian ibunya dari berbagai tuduhan orang-orang yang meragukan kesuciannya pada masa itu. Lanjutannya besok.",
        "Nabi Isa tumbuh dewasa dan diutus untuk menyeru seluruh Bani Israil agar kembali kepada ajaran tauhid yang telah jauh menyimpang pada masa itu. Allah menganugerahkannya berbagai mukjizat luar biasa, seperti menyembuhkan orang yang buta dan menderita penyakit kusta, bahkan menghidupkan seekor burung dari tanah liat atas izin Allah semata. Bagaimana kelanjutannya, simak besok.",
        "Sebagian kalangan penguasa dan pemuka agama pada masa itu menolak keras dakwah Nabi Isa dan diam-diam merencanakan sesuatu untuk mencelakainya. Namun sesuai dengan keyakinan yang diajarkan dalam Islam, Allah menyelamatkan dan mengangkat Nabi Isa langsung ke sisi-Nya, sehingga seluruh rencana jahat tersebut tidak pernah berhasil menimpanya sedikit pun. Lanjutannya besok.",
        "Kisah Nabi Isa mengajarkan kepada kita tentang kekuasaan Allah yang tidak pernah terbatas serta betapa pentingnya kesabaran dalam menghadapi berbagai penolakan ketika menyampaikan sebuah kebenaran. Hikmahnya, pertolongan Allah akan selalu datang bagi hamba-Nya yang tetap teguh berada di jalan kebenaran. Besok kita lanjut ke kisah Nabi Muhammad SAW, penutup seluruh para nabi.",
    ],
    "Muhammad": [
        "Nabi Muhammad SAW lahir di kota Mekah dalam keadaan yatim, dan sejak masih kecil telah dikenal sangat jujur oleh seluruh masyarakat di sekitarnya, hingga diberikan gelar Al-Amin yang berarti orang yang sangat dapat dipercaya. Ia tumbuh menjadi pribadi yang memiliki akhlak sangat mulia, meskipun harus menjalani kehidupan dalam kesederhanaan sejak usia dini. Lanjutannya besok.",
        "Pada usia empat puluh tahun, beliau menerima wahyu pertama kali di Gua Hira melalui perantara Malaikat Jibril, menandai dimulainya sebuah risalah kenabian besar yang akan mengubah jalannya sejarah dunia secara keseluruhan. Dakwah pada masa-masa awal dilakukan secara diam-diam kepada orang-orang terdekat, sebelum akhirnya disampaikan secara terbuka kepada khalayak ramai. Bagaimana kelanjutannya, simak besok.",
        "Dakwah Nabi Muhammad SAW menghadapi berbagai tantangan dan penolakan yang sangat keras dari kaum Quraisy, hingga akhirnya beliau beserta seluruh pengikutnya harus melakukan hijrah menuju kota Madinah. Di sanalah kemudian terbentuk sebuah masyarakat baru yang menjunjung tinggi nilai persaudaraan dan keadilan berdasarkan tuntunan Al-Qur'an yang telah diturunkan. Lanjutannya besok.",
        "Nabi Muhammad SAW wafat setelah berhasil menyampaikan risalah Islam secara sempurna kepada seluruh umat manusia, menjadi penutup dari seluruh rangkaian para nabi dan rasul yang pernah diutus Allah. Hikmah besar dari keseluruhan kisah 25 Nabi ini adalah bahwa setiap nabi diutus dengan penuh perjuangan dan kesabaran demi menegakkan ajaran tauhid, sebuah teladan abadi bagi seluruh umat manusia sepanjang masa. Series Kisah Nabi ini akan mengulang kembali dari awal besok, ikuti terus ya.",
    ],
}
